### ISSUE TITLE
Log freezes right after the invocation

### ISSUE THREAD

**Issue by kinzlaw** [FredHutch/bash-workbench#9]
The gif of [this part of the wiki](https://github.com/FredHutch/bash-workbench/wiki/Useful-Commands#run-a-tool) shows that after running a tool, the log will automatically scroll when there's new content being created. This is very handy to see the progress.

But in my environment, the log freezes right after the invocation, I have to open another shell and run `tail -f ._wb/output.txt` to see the live log. As in the below screenshot, `tail` is run in the right pane. Is there any configuration I've missed, or something wrong with the current version(0.0.14) of bash-workbench?

![image](https://user-images.githubusercontent.com/4575752/170268040-515c63cc-01be-4b63-bb76-56396a4a1d23.png)

**Comment by sminot** [comment]
Ah, this may have been a matter of the GIF not being totally clear. The intended behavior is actually that the next batch of logs will only show after you press enter. I tried for a while but couldn't figure out any way to get it to update automatically.

That said, it seemed like from your screenshot like the "View more logs" menu wasn't actually showing up for you -- is that correct?

Also, what version fo `bash-workbench` are you running? There was a bug with this that I had fixed in the last release, but I suspect that isn't the issue here.

Just to clarify, do you see the menu option for "View more logs?" Or is it just a blank line?

**Comment by kinzlaw** [comment]
I'm using Version 0.0.14, and I can see the menu option for "View more logs".

Well then, it's okay that I will stick to using `tail -f ._wb/output.txt` side by side. Just if bash-workbench can continually refresh the log itself, would be more convenient, haha.
